import type { PortfolioInput } from "./portfolio.schema";

export const starterPortfolio: PortfolioInput = {
  slug: "oliver",
  name: "Oliver Kean Palgue",
  title: "Full-Stack Developer / Software Engineer",
  bio: "I build full-stack web applications across product interfaces, APIs, databases, and third-party integrations, with a focus on reliable workflows, maintainable systems, and practical user experience.",
  location: "Baguio, Philippines",
  email: "oliverpalgue@gmail.com",
  phone: "+63 927 627 9969",
  websiteUrl: "https://oliverkean.github.io/portfolio/",
  githubUrl: "https://github.com/oliverkean",
  linkedinUrl: "https://www.linkedin.com/in/oliver-palgue",
  resumeUrl: "/resume-oliver-kean-palgue.pdf",
  heroImageUrl: "/icon.png",
  isPublished: true,
  projects: [
    {
      title: "Traffic Monitoring System",
      summary: "A real-time traffic monitoring web application that surfaces road conditions and helps users choose alternative routes.",
      description:
        "Designed and built traffic monitoring features using Laravel and Vue.js, structured database schemas, integrated RESTful APIs, and created technical documentation and system diagrams for maintenance and onboarding.",
      role: "Software Engineer Intern",
      stack: ["Laravel", "Vue.js", "REST APIs", "MySQL", "JavaScript"],
      liveUrl: "",
      repoUrl: "",
      imageUrl: "",
      featured: true,
      status: "Internship project",
      sortOrder: 0,
    },
    {
      title: "Swapii Bartering Platform",
      summary: "Frontend features for a bartering platform with real-time chat, trade management, authentication, and review flows.",
      description:
        "Built user-facing interfaces for marketplace-style exchange workflows, including chat, trade handling, authentication screens, and review/rating interactions.",
      role: "Frontend engineering",
      stack: ["React", "TypeScript", "JavaScript", "HTML5", "CSS3"],
      liveUrl: "",
      repoUrl: "",
      imageUrl: "",
      featured: true,
      status: "Project",
      sortOrder: 1,
    },
  ],
  experiences: [
    {
      company: "LogoLife",
      role: "Full-Stack Developer / Software Engineer",
      location: "Miami, FL / Remote",
      startDate: "July 2025",
      endDate: "Present",
      description:
        "Build and maintain full-stack product features for AcceptedX, a college counseling and education technology platform used by students, parents, counselors, and internal teams. Develop React, TypeScript, Tailwind CSS, and shadcn/ui interfaces while contributing to Node.js, Express.js, MERN, and NestJS backend features, APIs, and application logic. Translate feature requests into full-stack implementation plans, build meeting tools and proposal tracking workflows, expand Parent View and planning notification flows, improve surveys, application tracking, resume tools, signup flows, institution access, notifications, and internal team workflows. Work with HubSpot CRM/API, Stripe, webhooks, Redis, S3, Mailgun, Mapbox, BullMQ, OpenAI API, Docker workflows, SSH access with PEM keys, Git Bash, and .env configuration through terminal tools such as nano.",
      sortOrder: 0,
    },
    {
      company: "City Government of Baguio",
      role: "Software Engineer Intern",
      location: "Baguio City, Philippines",
      startDate: "April 2025",
      endDate: "May 2025",
      description:
        "Contributed to a real-time traffic monitoring web application using Laravel and Vue.js. Structured database schemas, integrated RESTful APIs, and created technical documentation and system diagrams for maintenance and onboarding.",
      sortOrder: 1,
    },
    {
      company: "University of Baguio",
      role: "Bachelor of Science in Computer Science",
      location: "Baguio City, Philippines",
      startDate: "Jun 2025",
      endDate: "",
      description: "Completed a Bachelor of Science in Computer Science.",
      sortOrder: 2,
    },
  ],
  skills: [
    { name: "React", category: "Frontend", level: 5, sortOrder: 0 },
    { name: "Next.js", category: "Frontend", level: 4, sortOrder: 1 },
    { name: "TypeScript", category: "Frontend", level: 5, sortOrder: 2 },
    { name: "JavaScript", category: "Frontend", level: 5, sortOrder: 3 },
    { name: "Tailwind CSS", category: "Frontend", level: 4, sortOrder: 4 },
    { name: "shadcn/ui", category: "Frontend", level: 4, sortOrder: 5 },
    { name: "HTML5", category: "Frontend", level: 5, sortOrder: 6 },
    { name: "CSS3", category: "Frontend", level: 5, sortOrder: 7 },
    { name: "Vue.js", category: "Frontend", level: 3, sortOrder: 8 },
    { name: "Bootstrap", category: "Frontend", level: 3, sortOrder: 9 },
    { name: "Node.js", category: "Backend/APIs", level: 4, sortOrder: 0 },
    { name: "Express.js", category: "Backend/APIs", level: 4, sortOrder: 1 },
    { name: "NestJS", category: "Backend/APIs", level: 4, sortOrder: 2 },
    { name: "Laravel", category: "Backend/APIs", level: 3, sortOrder: 3 },
    { name: "REST APIs", category: "Backend/APIs", level: 4, sortOrder: 4 },
    { name: "Webhooks", category: "Backend/APIs", level: 4, sortOrder: 5 },
    { name: "API Integration", category: "Backend/APIs", level: 4, sortOrder: 6 },
    { name: "MongoDB", category: "Databases", level: 4, sortOrder: 0 },
    { name: "PostgreSQL", category: "Databases", level: 4, sortOrder: 1 },
    { name: "Supabase PostgreSQL", category: "Databases", level: 3, sortOrder: 2 },
    { name: "MySQL", category: "Databases", level: 4, sortOrder: 3 },
    { name: "SQLite", category: "Databases", level: 3, sortOrder: 4 },
    { name: "SQL", category: "Databases", level: 4, sortOrder: 5 },
    { name: "NoSQL", category: "Databases", level: 4, sortOrder: 6 },
    { name: "HubSpot CRM/API", category: "Integrations/Services", level: 3, sortOrder: 0 },
    { name: "Stripe", category: "Integrations/Services", level: 3, sortOrder: 1 },
    { name: "OpenAI API", category: "Integrations/Services", level: 3, sortOrder: 2 },
    { name: "Mailgun", category: "Integrations/Services", level: 3, sortOrder: 3 },
    { name: "Mapbox", category: "Integrations/Services", level: 3, sortOrder: 4 },
    { name: "S3", category: "Integrations/Services", level: 3, sortOrder: 5 },
    { name: "Docker", category: "Deployment/Tools", level: 3, sortOrder: 0 },
    { name: "Vercel", category: "Deployment/Tools", level: 4, sortOrder: 1 },
    { name: "Supabase", category: "Deployment/Tools", level: 3, sortOrder: 2 },
    { name: "SSH", category: "Deployment/Tools", level: 3, sortOrder: 3 },
    { name: "PEM Keys", category: "Deployment/Tools", level: 3, sortOrder: 4 },
    { name: "Git Bash", category: "Deployment/Tools", level: 3, sortOrder: 5 },
    { name: "Environment Variables", category: "Deployment/Tools", level: 4, sortOrder: 6 },
    { name: "Redis", category: "Deployment/Tools", level: 4, sortOrder: 7 },
    { name: "BullMQ", category: "Deployment/Tools", level: 3, sortOrder: 8 },
    { name: "Cron", category: "Deployment/Tools", level: 3, sortOrder: 9 },
    { name: "Git", category: "Deployment/Tools", level: 5, sortOrder: 10 },
    { name: "GitHub", category: "Deployment/Tools", level: 5, sortOrder: 11 },
    { name: "Postman", category: "Deployment/Tools", level: 4, sortOrder: 12 },
    { name: "Cursor", category: "Deployment/Tools", level: 4, sortOrder: 13 },
    { name: "Claude Code", category: "Deployment/Tools", level: 4, sortOrder: 14 },
    { name: "Codex", category: "Deployment/Tools", level: 4, sortOrder: 15 },
    { name: "Visual Studio Code", category: "Deployment/Tools", level: 5, sortOrder: 16 },
  ],
};
