import type { PortfolioInput } from "./portfolio.schema";

export const starterPortfolio: PortfolioInput = {
  slug: "oliver",
  name: "Oliver",
  title: "Full Stack Developer",
  bio: "I build reliable, user-friendly web applications with strong product instincts, clean systems thinking, and a focus on maintainable delivery.",
  location: "New York, NY",
  email: "oliver@example.com",
  phone: "",
  websiteUrl: "https://example.com",
  githubUrl: "https://github.com/oliver",
  linkedinUrl: "https://linkedin.com/in/oliver",
  resumeUrl: "",
  heroImageUrl: "",
  isPublished: true,
  projects: [
    {
      title: "ShipFast",
      summary: "A deployment tracker that helps product teams monitor releases from pull request to production.",
      description: "Built a release dashboard with audit history, deployment health, and team handoff workflows.",
      role: "Full stack engineering",
      stack: ["Next.js", "TypeScript", "PostgreSQL", "Prisma"],
      liveUrl: "https://example.com",
      repoUrl: "https://github.com/oliver/shipfast",
      imageUrl: "",
      featured: true,
      status: "Published",
      sortOrder: 0,
    },
    {
      title: "Pulse Analytics",
      summary: "A lightweight analytics console for operational teams to review trends and segment activity.",
      description: "Created data tables, filters, and summary views backed by normalized PostgreSQL data.",
      role: "Backend and UI",
      stack: ["React", "Node.js", "PostgreSQL", "Tailwind CSS"],
      liveUrl: "",
      repoUrl: "https://github.com/oliver/pulse-analytics",
      imageUrl: "",
      featured: true,
      status: "Published",
      sortOrder: 1,
    },
    {
      title: "DevNotes",
      summary: "A markdown knowledge base for engineers to organize snippets, decisions, and implementation notes.",
      description: "Implemented editor state, search, tagging, and public sharing workflows.",
      role: "Product engineering",
      stack: ["Next.js", "Prisma", "Tailwind CSS"],
      liveUrl: "",
      repoUrl: "https://github.com/oliver/devnotes",
      imageUrl: "",
      featured: false,
      status: "Draft",
      sortOrder: 2,
    },
  ],
  experiences: [
    {
      company: "Northstar Labs",
      role: "Software Engineer",
      location: "Remote",
      startDate: "2023",
      endDate: "Present",
      description: "Built customer-facing product workflows, internal APIs, and database-backed features across the product surface.",
      sortOrder: 0,
    },
    {
      company: "Brightlayer",
      role: "Frontend Developer",
      location: "New York, NY",
      startDate: "2021",
      endDate: "2023",
      description: "Delivered accessible React interfaces, reusable component patterns, and performance improvements for SaaS dashboards.",
      sortOrder: 1,
    },
  ],
  skills: [
    { name: "React", category: "Frontend", level: 5, sortOrder: 0 },
    { name: "TypeScript", category: "Frontend", level: 5, sortOrder: 1 },
    { name: "JavaScript", category: "Frontend", level: 5, sortOrder: 2 },
    { name: "Tailwind CSS", category: "Frontend", level: 4, sortOrder: 3 },
    { name: "shadcn/ui", category: "Frontend", level: 4, sortOrder: 4 },
    { name: "HTML5", category: "Frontend", level: 5, sortOrder: 5 },
    { name: "CSS3", category: "Frontend", level: 5, sortOrder: 6 },
    { name: "Vue.js", category: "Frontend", level: 3, sortOrder: 7 },
    { name: "Bootstrap", category: "Frontend", level: 3, sortOrder: 8 },
    { name: "Node.js", category: "Backend/APIs", level: 4, sortOrder: 0 },
    { name: "Express.js", category: "Backend/APIs", level: 4, sortOrder: 1 },
    { name: "NestJS", category: "Backend/APIs", level: 4, sortOrder: 2 },
    { name: "Laravel", category: "Backend/APIs", level: 3, sortOrder: 3 },
    { name: "REST APIs", category: "Backend/APIs", level: 4, sortOrder: 4 },
    { name: "Webhooks", category: "Backend/APIs", level: 4, sortOrder: 5 },
    { name: "API Integration", category: "Backend/APIs", level: 4, sortOrder: 6 },
    { name: "MongoDB", category: "Databases", level: 4, sortOrder: 0 },
    { name: "MySQL", category: "Databases", level: 4, sortOrder: 1 },
    { name: "SQLite", category: "Databases", level: 3, sortOrder: 2 },
    { name: "SQL", category: "Databases", level: 4, sortOrder: 3 },
    { name: "NoSQL", category: "Databases", level: 4, sortOrder: 4 },
    { name: "Redis", category: "Tools", level: 4, sortOrder: 0 },
    { name: "S3", category: "Tools", level: 3, sortOrder: 1 },
    { name: "Mailgun", category: "Tools", level: 3, sortOrder: 2 },
    { name: "Mapbox", category: "Tools", level: 3, sortOrder: 3 },
    { name: "HubSpot CRM/API", category: "Tools", level: 3, sortOrder: 4 },
    { name: "Git", category: "Tools", level: 5, sortOrder: 5 },
    { name: "GitHub", category: "Tools", level: 5, sortOrder: 6 },
    { name: "Postman", category: "Tools", level: 4, sortOrder: 7 },
    { name: "BullMQ", category: "Tools", level: 3, sortOrder: 8 },
    { name: "Cron", category: "Tools", level: 3, sortOrder: 9 },
    { name: "Codex", category: "Tools", level: 4, sortOrder: 10 },
    { name: "Cursor", category: "Tools", level: 4, sortOrder: 11 },
    { name: "Claude Code", category: "Tools", level: 4, sortOrder: 12 },
    { name: "Visual Studio Code", category: "Tools", level: 5, sortOrder: 13 },
    { name: "OpenAI API", category: "Tools", level: 3, sortOrder: 14 },
  ],
};
