import type { PortfolioInput } from "./portfolio.schema";

export const starterPortfolio: PortfolioInput = {
  slug: "oliver",
  name: "Oliver Palgue",
  title: "Software Engineer",
  bio: "I build full-stack web applications across product interfaces, APIs, databases, and third-party integrations, with a focus on reliable workflows, maintainable systems, and practical user experience.",
  location: "Baguio, Philippines",
  email: "oliverpalgue@gmail.com",
  phone: "+63 927 627 9969",
  websiteUrl: "https://oliverkean.github.io/portfolio/",
  githubUrl: "https://github.com/oliverkean",
  linkedinUrl: "https://www.linkedin.com/in/oliver-palgue",
  resumeUrl: "/resume-oliver-kean-palgue.pdf",
  heroImageUrl: "/icon.png",
  isPublished: true,
  projects: [
    {
      title: "Traffic Monitoring System",
      summary: "A real-time traffic monitoring web application that surfaces road conditions and helps users choose alternative routes.",
      description:
        "Designed and built traffic monitoring features using Laravel and Vue.js, structured database schemas, integrated RESTful APIs, and created technical documentation and system diagrams for maintenance and onboarding.",
      role: "Software Engineer Intern",
      stack: ["Laravel", "Vue.js", "REST APIs", "MySQL", "JavaScript"],
      liveUrl: "",
      repoUrl: "",
      imageUrl: "",
      featured: true,
      status: "Internship project",
      sortOrder: 0,
    },
    {
      title: "Swapii Bartering Platform",
      summary: "Frontend features for a bartering platform with real-time chat, trade management, authentication, and review flows.",
      description:
        "Built user-facing interfaces for marketplace-style exchange workflows, including chat, trade handling, authentication screens, and review/rating interactions.",
      role: "Frontend engineering",
      stack: ["React", "TypeScript", "JavaScript", "HTML5", "CSS3"],
      liveUrl: "",
      repoUrl: "",
      imageUrl: "",
      featured: true,
      status: "Project",
      sortOrder: 1,
    },
  ],
  experiences: [
    {
      company: "LogoLife",
      role: "Software Engineer",
      location: "Miami, FL / Remote",
      startDate: "Jul 2025",
      endDate: "Present",
      description:
        "Build and maintain full-stack product features for AcceptedX using React, TypeScript, Tailwind CSS, shadcn/ui, Node.js, Express.js, MERN, and NestJS. Translate feature requests into implementation plans across UI flow, backend logic, API handling, data requirements, and third-party integrations including HubSpot CRM/API, webhooks, Redis, S3, Mailgun, Mapbox, BullMQ, and OpenAI API.",
      sortOrder: 0,
    },
    {
      company: "City Government of Baguio",
      role: "Software Engineer Intern",
      location: "Baguio City, Philippines",
      startDate: "Apr 2025",
      endDate: "May 2025",
      description:
        "Contributed to a real-time traffic monitoring web application using Laravel and Vue.js. Structured database schemas, integrated RESTful APIs, and created technical documentation and system diagrams for maintenance and onboarding.",
      sortOrder: 1,
    },
    {
      company: "University of Baguio",
      role: "Bachelor of Science in Computer Science",
      location: "Baguio City, Philippines",
      startDate: "Jun 2025",
      endDate: "",
      description: "Completed a Bachelor of Science in Computer Science.",
      sortOrder: 2,
    },
  ],
  skills: [
    { name: "React", category: "Frontend", level: 5, sortOrder: 0 },
    { name: "TypeScript", category: "Frontend", level: 5, sortOrder: 1 },
    { name: "JavaScript", category: "Frontend", level: 5, sortOrder: 2 },
    { name: "Tailwind CSS", category: "Frontend", level: 4, sortOrder: 3 },
    { name: "shadcn/ui", category: "Frontend", level: 4, sortOrder: 4 },
    { name: "HTML5", category: "Frontend", level: 5, sortOrder: 5 },
    { name: "CSS3", category: "Frontend", level: 5, sortOrder: 6 },
    { name: "Vue.js", category: "Frontend", level: 3, sortOrder: 7 },
    { name: "Bootstrap", category: "Frontend", level: 3, sortOrder: 8 },
    { name: "Node.js", category: "Backend/APIs", level: 4, sortOrder: 0 },
    { name: "Express.js", category: "Backend/APIs", level: 4, sortOrder: 1 },
    { name: "NestJS", category: "Backend/APIs", level: 4, sortOrder: 2 },
    { name: "Laravel", category: "Backend/APIs", level: 3, sortOrder: 3 },
    { name: "REST APIs", category: "Backend/APIs", level: 4, sortOrder: 4 },
    { name: "Webhooks", category: "Backend/APIs", level: 4, sortOrder: 5 },
    { name: "API Integration", category: "Backend/APIs", level: 4, sortOrder: 6 },
    { name: "MongoDB", category: "Databases", level: 4, sortOrder: 0 },
    { name: "MySQL", category: "Databases", level: 4, sortOrder: 1 },
    { name: "SQLite", category: "Databases", level: 3, sortOrder: 2 },
    { name: "SQL", category: "Databases", level: 4, sortOrder: 3 },
    { name: "NoSQL", category: "Databases", level: 4, sortOrder: 4 },
    { name: "Redis", category: "Tools", level: 4, sortOrder: 0 },
    { name: "S3", category: "Tools", level: 3, sortOrder: 1 },
    { name: "Mailgun", category: "Tools", level: 3, sortOrder: 2 },
    { name: "Mapbox", category: "Tools", level: 3, sortOrder: 3 },
    { name: "HubSpot CRM/API", category: "Tools", level: 3, sortOrder: 4 },
    { name: "Git", category: "Tools", level: 5, sortOrder: 5 },
    { name: "GitHub", category: "Tools", level: 5, sortOrder: 6 },
    { name: "Postman", category: "Tools", level: 4, sortOrder: 7 },
    { name: "BullMQ", category: "Tools", level: 3, sortOrder: 8 },
    { name: "Cron", category: "Tools", level: 3, sortOrder: 9 },
    { name: "Codex", category: "Tools", level: 4, sortOrder: 10 },
    { name: "Cursor", category: "Tools", level: 4, sortOrder: 11 },
    { name: "Claude Code", category: "Tools", level: 4, sortOrder: 12 },
    { name: "Visual Studio Code", category: "Tools", level: 5, sortOrder: 13 },
    { name: "OpenAI API", category: "Tools", level: 3, sortOrder: 14 },
  ],
};
